// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZeDoO2dB3-gXHLG3EB9IdVLykwl_4FQ',
    appId: '1:557688206303:web:4059c1c4a2e19f8d6aca6a',
    messagingSenderId: '557688206303',
    projectId: 'taskmanager-33dfe',
    authDomain: 'taskmanager-33dfe.firebaseapp.com',
    storageBucket: 'taskmanager-33dfe.appspot.com',
    measurementId: 'G-B9149Q9DGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCURflNFZoVMtD8uFmgBNsie4ba7YPobik',
    appId: '1:557688206303:android:d94e6f49a01b22b96aca6a',
    messagingSenderId: '557688206303',
    projectId: 'taskmanager-33dfe',
    storageBucket: 'taskmanager-33dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2sF89oB24QyE0FaYuy2E40Gxfu-2QAE',
    appId: '1:557688206303:ios:f8703d858517589c6aca6a',
    messagingSenderId: '557688206303',
    projectId: 'taskmanager-33dfe',
    storageBucket: 'taskmanager-33dfe.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2sF89oB24QyE0FaYuy2E40Gxfu-2QAE',
    appId: '1:557688206303:ios:f8703d858517589c6aca6a',
    messagingSenderId: '557688206303',
    projectId: 'taskmanager-33dfe',
    storageBucket: 'taskmanager-33dfe.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ZeDoO2dB3-gXHLG3EB9IdVLykwl_4FQ',
    appId: '1:557688206303:web:b98d72b3897257136aca6a',
    messagingSenderId: '557688206303',
    projectId: 'taskmanager-33dfe',
    authDomain: 'taskmanager-33dfe.firebaseapp.com',
    storageBucket: 'taskmanager-33dfe.appspot.com',
    measurementId: 'G-R26CFRTLTP',
  );
}
